#!/bin/sh


# shellcheck disable=SC2046

fieldalignment -fix  ./...
if [ $? -eq 0 ]; then
  exit 1
fi

go install golang.org/x/vuln/cmd/govulncheck@latest
govulncheck ./...

go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
golangci-lint run ./...

